export const GET_NEW_CITY_DATA_SUCCESS = 'GET_NEW_CITY_DATA_SUCCESS';
export const GET_NEW_CITY_DATA_FAILED = 'GET_NEW_CITY_DATA_FAILED';
export const ADD_CITY_IN_LIST = 'ADD_CITY_IN_LIST';
export const DELETE_CITY_FROM_LIST = 'DELETE_CITY_FROM_LIST';